### ISSUE TITLE
Setting up config.py

### ISSUE THREAD

**Issue by kbedoway** [kbedoway/youtube_api_temp#1]
**User Story:**
The config.py file will store the API key ID and the youtube.py file will test to make sure the value from the config.py file prints correctly.

* Persona: Users of program
* Feature: Users can search on Youtube
* Business value: Youtube searchability

**Tasks:**
- [ ] Add config.py file
- [ ] Add youtube.py file
- [ ] Run youtube.py and check results

**Acceptance Criteria:**
1. Only works for this program

**Acceptance Tests:**
1. Users should be able to change API key ID
