### ISSUE TITLE
Basic Youtube Search

### ISSUE THREAD

**Issue by kbedoway** [kbedoway/youtube_api_temp#3]
**User Story:**
The youtube.py file will allow users to search based on query terms and maximum result values.

* Persona: Users of program
* Feature: Users can search on Youtube
* Business value: Youtube searchability by query terms and maximum result values

**Tasks:**
- [ ] Create virtual environment
- [ ] Install google-api-python-client
- [ ] Export virtual environment to requirements.txt
- [ ] Edit youtube.py file
- [ ] Run youtube.py and check results

**Acceptance Criteria:**
1. Only works for this program

**Acceptance Tests:**
1. Users should be able to search by query terms and maximum result values
